export const languages = [
	'English (US)',
	'English (UK)',
	'French',
	'German',
	'Italian',
	'Spanish',
	'Dutch',
	'Danish',
	'Swedish',
	'Norwegian',
	'Finnish',
	'Hebrew',
	'Russian',
	'Portuguese',
	'Japanese',
	'Polish',
	'Traditional Chinese',
	'Simplified Chinese',
	'Thai',
	'Korean',
	'Czech',
] as const;

export const defaultFileName = {
	TGA: '[image file]',
	NREF: '[name reference]',
	BCON: '[behavior constant]',
	BHAV: '[behavior function]',
	CTSS: '[catalogue description]',
	GLOB: '[global data]',
	OBJD: '[object data]',
	OBJF: '[object functions]',
	STR: '[text lists]',
};
