import fs from 'fs/promises';
import path from 'path';
import { deserialize, serialize } from './trcn.js';

const fileData = {
  filename: 'Special Outfit IDs',
  version: 78,
  items: [
    {
      constId: 0,
      constName: 'Werewolf - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 1,
      constName: 'Werewolf - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 2,
      constName: 'Werewolf - Servo - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 3,
      constName: 'Werewolf - Servo - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 4,
      constName: 'Electrocuted - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 5,
      constName: 'Electrocuted - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 6,
      constName: 'Vampire - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 7,
      constName: 'Vampire - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 8,
      constName: 'Overheated - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 9,
      constName: 'Overheated - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 10,
      constName: 'Freeze - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 11,
      constName: 'Freeze - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 12,
      constName: 'Frozen Cheeks - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 13,
      constName: 'Frozen Cheeks - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 14,
      constName: 'Plantsim - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 15,
      constName: 'Plantsim - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 16,
      constName: 'Plantsim - Wilted T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 17,
      constName: 'Plantsim - Wilted T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 18,
      constName: 'Tanned - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 19,
      constName: 'Tanned - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 20,
      constName: 'Sunburn - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 21,
      constName: 'Sunburn - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 22,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 23,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 24,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 25,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 26,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 27,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 28,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 29,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 30,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 31,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 32,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 33,
      constName: '',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 34,
      constName: 'Plantman Clothes - T[0]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
    {
      constId: 35,
      constName: 'Plantman Clothes - T[1]',
      value: 0,
      minValue: 0,
      maxValue: 0,
      used: 1,
      desc: '',
    },
  ],
};

const filePath = path.join(__dirname, 'fixtures/valid.trcn');

describe('TRCN', () => {
  it('can deserialize TRCN files', async () => {
    const buf = (await fs.readFile(filePath)).buffer;
    expect(deserialize(buf)).toEqual(fileData);
  });

  it('can serialize TRCN files', async () => {
    const serializedFile = serialize(fileData);
    await expect(serializedFile).toMatchFile(filePath);
  });
});
